name: libmelee test cases

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - name: Install dependencies
      run: python3 -m pip install --upgrade pip setuptools wheel
    # - name: Test with pytest
    #   run: python3 test.py
    - name: Where am i
      run: ls -l
